import puzzle1 from '../src/06/puzzle1';
import puzzle2 from '../src/06/puzzle2';

test('Example input', () => {
  const input = `....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...`;
  expect(puzzle1(input)).toBe(41);
  expect(puzzle2(input)).toBe(6);
});
