import puzzle1 from '../src/08/puzzle1';
import puzzle2 from '../src/08/puzzle2';

describe('Testing several inputs', () => {
  test('Example input 1', () => {
    const input = `..........
..........
..........
....a.....
..........
.....a....
..........
..........
..........
..........`;
    expect(puzzle1(input)).toBe(2);
  });

  test('Example input 2', () => {
    const input = `..........
..........
..........
....a.....
........a.
.....a....
..........
..........
..........
..........`;
    expect(puzzle1(input)).toBe(4);
  });

  test('Example input 3', () => {
    const input = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`;
    expect(puzzle1(input)).toBe(14);
    expect(puzzle2(input)).toBe(34);
  });

  test('Example input 4', () => {
    const input = `T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........`;
    expect(puzzle2(input)).toBe(9);
  });
});
